export * from './indice-de-efectividad-anual';
export * from './volumen-de-originacion-real';
export * from './desviacion-operativa';
export * from './mezcla-de-portafolio-financiero';
export * from './cumplimiento-mensual-de-meta';
export * from './participacion-por-canal';
export * from './ranking-de-jefes-de-ventas';
export * from './ranking-de-promotores';
export * from './desempeno-por-seccion';
